-- Corrigir função hv_insert removendo campo "email" inexistente
DROP FUNCTION IF EXISTS public.hv_insert(jsonb) CASCADE;

CREATE OR REPLACE FUNCTION public.hv_insert(p_data jsonb)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result json;
  v_inserted_id uuid;
BEGIN
  INSERT INTO public.historico_vendas (
    id_unico,
    numero_pedido,
    sku_produto,
    descricao,
    quantidade,
    valor_unitario,
    valor_total,
    cliente_nome,
    cliente_documento,
    status,
    observacoes,
    data_pedido,
    ncm,
    codigo_barras,
    pedido_id,
    cpf_cnpj,
    valor_frete,
    data_prevista,
    obs,
    obs_interna,
    cidade,
    uf,
    url_rastreamento,
    situacao,
    codigo_rastreamento,
    numero_ecommerce,
    valor_desconto,
    numero_venda,
    sku_estoque,
    sku_kit,
    qtd_kit,
    total_itens,
    empresa,
    integration_account_id,
    meta,
    nome_completo,
    ultima_atualizacao,
    quantidade_total,
    titulo_produto,
    valor_pago,
    frete_pago_cliente,
    receita_flex_bonus,
    custo_envio_seller,
    desconto_cupom,
    taxa_marketplace,
    valor_liquido_vendedor,
    metodo_pagamento,
    status_pagamento,
    tipo_pagamento,
    status_mapeamento,
    quantidade_kit,
    status_baixa,
    status_envio,
    logistic_mode_principal,
    tipo_logistico,
    tipo_metodo_envio,
    tipo_entrega,
    substatus_estado_atual,
    modo_envio_combinado,
    metodo_envio_combinado,
    created_by,
    origem,
    raw,
    skus_produtos,
    rua,
    numero,
    bairro,
    cep,
    quantidade_itens,
    delivery_type,
    substatus_detail,
    shipping_method,
    shipping_mode,
    date_created,
    pack_id,
    pickup_id,
    pack_status,
    pack_status_detail,
    tags,
    last_updated,
    local_estoque_id,
    local_estoque_nome,
    local_estoque,
    titulo_anuncio,
    conditions,
    shipping_substatus,
    logistic_type,
    status_insumos,
    custo_fixo_meli,
    marketplace_origem,
    power_seller_status,
    level_id,
    shipping_shipping_status,
    raw_data
  ) VALUES (
    p_data->>'id_unico',
    p_data->>'numero_pedido',
    p_data->>'sku_produto',
    p_data->>'descricao',
    COALESCE((p_data->>'quantidade')::integer, 0),
    COALESCE((p_data->>'valor_unitario')::numeric, 0),
    COALESCE((p_data->>'valor_total')::numeric, 0),
    p_data->>'cliente_nome',
    p_data->>'cliente_documento',
    p_data->>'status',
    p_data->>'observacoes',
    CASE WHEN p_data->>'data_pedido' IS NOT NULL THEN (p_data->>'data_pedido')::date ELSE NULL END,
    p_data->>'ncm',
    p_data->>'codigo_barras',
    p_data->>'pedido_id',
    p_data->>'cpf_cnpj',
    COALESCE((p_data->>'valor_frete')::numeric, 0),
    CASE WHEN p_data->>'data_prevista' IS NOT NULL THEN (p_data->>'data_prevista')::date ELSE NULL END,
    p_data->>'obs',
    p_data->>'obs_interna',
    p_data->>'cidade',
    p_data->>'uf',
    p_data->>'url_rastreamento',
    p_data->>'situacao',
    p_data->>'codigo_rastreamento',
    p_data->>'numero_ecommerce',
    COALESCE((p_data->>'valor_desconto')::numeric, 0),
    p_data->>'numero_venda',
    p_data->>'sku_estoque',
    p_data->>'sku_kit',
    COALESCE((p_data->>'qtd_kit')::integer, 0),
    COALESCE((p_data->>'total_itens')::integer, 0),
    p_data->>'empresa',
    CASE WHEN p_data->>'integration_account_id' IS NOT NULL AND p_data->>'integration_account_id' != '' THEN (p_data->>'integration_account_id')::uuid ELSE NULL END,
    CASE WHEN p_data->'meta' IS NOT NULL THEN p_data->'meta' ELSE NULL END,
    p_data->>'nome_completo',
    CASE WHEN p_data->>'ultima_atualizacao' IS NOT NULL THEN (p_data->>'ultima_atualizacao')::timestamptz ELSE NULL END,
    COALESCE((p_data->>'quantidade_total')::integer, 0),
    p_data->>'titulo_produto',
    COALESCE((p_data->>'valor_pago')::numeric, 0),
    COALESCE((p_data->>'frete_pago_cliente')::numeric, 0),
    COALESCE((p_data->>'receita_flex_bonus')::numeric, 0),
    COALESCE((p_data->>'custo_envio_seller')::numeric, 0),
    COALESCE((p_data->>'desconto_cupom')::numeric, 0),
    COALESCE((p_data->>'taxa_marketplace')::numeric, 0),
    COALESCE((p_data->>'valor_liquido_vendedor')::numeric, 0),
    p_data->>'metodo_pagamento',
    p_data->>'status_pagamento',
    p_data->>'tipo_pagamento',
    p_data->>'status_mapeamento',
    COALESCE((p_data->>'quantidade_kit')::integer, 0),
    p_data->>'status_baixa',
    p_data->>'status_envio',
    p_data->>'logistic_mode_principal',
    p_data->>'tipo_logistico',
    p_data->>'tipo_metodo_envio',
    p_data->>'tipo_entrega',
    p_data->>'substatus_estado_atual',
    p_data->>'modo_envio_combinado',
    p_data->>'metodo_envio_combinado',
    CASE WHEN p_data->>'created_by' IS NOT NULL AND p_data->>'created_by' != '' THEN (p_data->>'created_by')::uuid ELSE NULL END,
    p_data->>'origem',
    CASE WHEN p_data->'raw' IS NOT NULL THEN p_data->'raw' ELSE NULL END,
    p_data->>'skus_produtos',
    p_data->>'rua',
    p_data->>'numero',
    p_data->>'bairro',
    p_data->>'cep',
    COALESCE((p_data->>'quantidade_itens')::integer, 0),
    p_data->>'delivery_type',
    p_data->>'substatus_detail',
    p_data->>'shipping_method',
    p_data->>'shipping_mode',
    CASE WHEN p_data->>'date_created' IS NOT NULL THEN (p_data->>'date_created')::timestamptz ELSE NULL END,
    p_data->>'pack_id',
    p_data->>'pickup_id',
    p_data->>'pack_status',
    p_data->>'pack_status_detail',
    CASE WHEN p_data->'tags' IS NOT NULL AND jsonb_typeof(p_data->'tags') = 'array' THEN ARRAY(SELECT jsonb_array_elements_text(p_data->'tags')) ELSE NULL END,
    CASE WHEN p_data->>'last_updated' IS NOT NULL THEN (p_data->>'last_updated')::timestamptz ELSE NULL END,
    CASE WHEN p_data->>'local_estoque_id' IS NOT NULL AND p_data->>'local_estoque_id' != '' THEN (p_data->>'local_estoque_id')::uuid ELSE NULL END,
    p_data->>'local_estoque_nome',
    p_data->>'local_estoque',
    p_data->>'titulo_anuncio',
    p_data->>'conditions',
    p_data->>'shipping_substatus',
    p_data->>'logistic_type',
    p_data->>'status_insumos',
    COALESCE((p_data->>'custo_fixo_meli')::numeric, 0),
    p_data->>'marketplace_origem',
    p_data->>'power_seller_status',
    p_data->>'level_id',
    p_data->>'shipping_shipping_status',
    CASE WHEN p_data->'raw_data' IS NOT NULL THEN p_data->'raw_data' ELSE NULL END
  )
  RETURNING id INTO v_inserted_id;
  
  RETURN json_build_object(
    'success', true, 
    'id', v_inserted_id,
    'message', 'Histórico de venda inserido com sucesso'
  );
  
EXCEPTION 
  WHEN OTHERS THEN
    RAISE WARNING 'Erro ao inserir histórico: % | SQLSTATE: %', SQLERRM, SQLSTATE;
    RETURN json_build_object(
      'success', false, 
      'error', SQLERRM,
      'sqlstate', SQLSTATE
    );
END;
$$;

-- Grant permissions
GRANT EXECUTE ON FUNCTION public.hv_insert(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.hv_insert(jsonb) TO service_role;