-- Adicionar novos campos na tabela oms_sales_reps para o formulário completo

ALTER TABLE public.oms_sales_reps
ADD COLUMN IF NOT EXISTS fantasia TEXT,
ADD COLUMN IF NOT EXISTS codigo TEXT,
ADD COLUMN IF NOT EXISTS tipo_pessoa TEXT DEFAULT 'PJ' CHECK (tipo_pessoa IN ('PF', 'PJ')),
ADD COLUMN IF NOT EXISTS doc TEXT,
ADD COLUMN IF NOT EXISTS contribuinte TEXT DEFAULT '9',
ADD COLUMN IF NOT EXISTS inscricao_estadual TEXT,
ADD COLUMN IF NOT EXISTS cep TEXT,
ADD COLUMN IF NOT EXISTS cidade TEXT,
ADD COLUMN IF NOT EXISTS uf TEXT,
ADD COLUMN IF NOT EXISTS endereco TEXT,
ADD COLUMN IF NOT EXISTS bairro TEXT,
ADD COLUMN IF NOT EXISTS numero TEXT,
ADD COLUMN IF NOT EXISTS complemento TEXT,
ADD COLUMN IF NOT EXISTS celular TEXT,
ADD COLUMN IF NOT EXISTS situacao TEXT DEFAULT 'ativo_com_acesso' CHECK (situacao IN ('ativo_com_acesso', 'ativo_sem_acesso', 'inativo')),
ADD COLUMN IF NOT EXISTS deposito TEXT DEFAULT 'padrao',
ADD COLUMN IF NOT EXISTS email_comunicacoes TEXT,
ADD COLUMN IF NOT EXISTS usuario_sistema TEXT,
ADD COLUMN IF NOT EXISTS acesso_restrito_horario BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS acesso_restrito_ip BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS perfil_contato TEXT DEFAULT 'qualquer',
ADD COLUMN IF NOT EXISTS modulos_acesso TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS regra_liberacao_comissao TEXT DEFAULT 'parcial_parcelas',
ADD COLUMN IF NOT EXISTS tipo_comissao TEXT DEFAULT 'aliquota_fixa' CHECK (tipo_comissao IN ('aliquota_fixa', 'aliquota_descontos')),
ADD COLUMN IF NOT EXISTS pode_incluir_produtos_nao_cadastrados BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS pode_emitir_cobrancas BOOLEAN DEFAULT false;